### ISSUE TITLE
Changes made in the extension won't save (Opera GX browser)

### ISSUE THREAD

**Issue by FoolishKovane** [Daw588/vanita#6] opened 2024-02-21 20:02 UTC
When I try to do any changes in the extension, they get discarded as soon as I reopen it, which is a bit frustrating.
I tested on another browser (Chrome), it works there. Might be an issue related to my browser, then

I looked into it a little, might just be an issue with the current version of the browser.
I've been editing this like crazy 💀 the issue showed up on Chrome now

**Comment by Daw588** [comment] 2024-02-21 21:14
I had several people report issues with Opera GX. I will look it into it, but it's difficult to work it out, since it works sometimes, and sometimes it doesn't, and there isn't any clear error message. Right now, it would be great if you could provide me some logs so that I can look into them. Here are the steps:

![image](https://github.com/Daw588/vanita/assets/44325281/6ddc35cc-def1-4730-b33c-ba013c575989)

![image](https://github.com/Daw588/vanita/assets/44325281/6c340ebd-1fe8-4b64-b93d-ce0a3b347cc4)

![image](https://github.com/Daw588/vanita/assets/44325281/bbdbee43-055b-4552-a99b-09c42dbb4740)

![image](https://github.com/Daw588/vanita/assets/44325281/eb9ebfd6-8d3a-4cf8-9554-9d81999890a9)

![image](https://github.com/Daw588/vanita/assets/44325281/629436e3-837f-4d52-acd8-99c9cc269f56)

**Comment by FoolishKovane** [comment] 2024-02-21 23:18
![image_2024-02-21_191630646](https://github.com/Daw588/vanita/assets/160783961/cd769923-7fcb-4bcf-a039-cc63d8eb0275)
For Vanita, it's a failure to load assets.

On my roblox.com console, it's mostly my adblocker at work. Seems to be doing fine on there.

**Comment by Daw588** [comment] 2024-02-22 01:54
Did you do that after trying to save an outfit?

**Comment by FoolishKovane** [comment] 2024-02-22 02:04
No, but when I do, another error is added. Here is the log with this new error included.
![image_2024-02-21_220432702](https://github.com/Daw588/vanita/assets/160783961/10cd1ac9-3232-4642-9225-922e204cb69b)

**Comment by Daw588** [comment] 2024-02-22 02:07
Thank you so much, this is very helpful to fix the issue. I will follow up with you once I have a solution.

**Comment by FoolishKovane** [comment] 2024-02-22 02:08
Very well, thank you so much. 👍

**Comment by Daw588** [comment] 2024-02-22 05:35
This should be fixed in [v3.1.0](https://github.com/Daw588/vanita/releases/tag/v3.1.0) release. Let me know if the issue is fixed on your end.

**Comment by FoolishKovane** [comment] 2024-02-22 18:44
It worked! Sorry for the late reply, I was busy. It worked, though.
You should update the Google Webstore extension. Thanks so much.

**Comment by Daw588** [comment] 2024-02-22 18:51
Good to hear. The Google Web Store version will be updated, just wanted to verify that the update fixed for you.

**Closed by Daw588** 2024-02-22 18:51 UTC
Labels: bug
